


<?php if($_SESSION['alias'] == ""){
    echo '<div class="alert alert-danger" style="color: #a94442; background-color: #f2dede; border-color: #ebccd1; padding: 10px; width: 100%; display: block;">
             <strong>ALERTA!</strong> Por favor insira o número de telefone
          </div>';
}else{
    echo '<img src="https://seguro.eupago.pt/repositorio/imagens/MBWay.png" class="v-middle">';
}?>


<!--<table cellpadding="0" cellspacing="0" border="0" style="width: 370px; color:#666; background-color: #f1f1f1; height: 50px; margin: 10px 0; border: 0px solid #d70510;">
    <tr>
        <td style="border: 0; padding:5px; margin:0; background-color: #D80410; color: #f1f1f1; text-align: center; font-size:small;" colspan="3">Pagamento por MB Way</td>
    </tr>
    <tr>
        <td style="border: 0; padding:10px; margin:0; color: #666; font-size:small;">Se ainda não instalou  a aplicação no smartphone ou ainda não aderiu ao serviço mbway, por favor consulte este <a target="_blank"  href="https://www.mbway.pt/" >link</a>. </p></td>
    </tr>
</table>-->
