<ul id="payment_info_<?php echo $this->getMethodCode() ?>">
    <li>
	<h4>Mbway</h4>
    <?php echo $this->__('Vai receber nos seus dispositivos inscritos no MB WAY um pedido de pagamento. Para validar a compra basta aceitar e introduzir o seu PIN MB WAY.') ?>
	<!-- <p><?php //echo $this->__('Para saber mais acerca do mbway por favor clique ') ?><a target="blank" href="https://www.mbway.pt/">aqui</a></p> -->
    </li>
</ul>