<?php $_code=$this->getMethodCode(); echo $this->getMethod()->getConfigData('message');?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
	<li>
		<span class="input-box">
		<label for="<?php echo $_code ?>_mbway_phone_number" class="required"><em>*</em><?php echo $this->__('Numero Mbway') ?></label>
			<input type="text" title="<?php echo $this->__('Número Mbway:') ?>" class="input-text required-entry" id="<?php echo $_code ?>_mbway_phone_number" name="payment[mbway_phone_number]" value="<?php echo $this->htmlEscape($this->getInfoData('mbway_phone_number')) ?>" />
		</span>
	</li>
</ul>

