<?php $_code=$this->getMethodCode(); echo $this->getMethod()->getConfigData('message'); ?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display:none">
        <table cellpadding="0" cellspacing="0" border="0" style="max-width: 370px; color:#666; background-color: #f1f1f1; height: 50px; margin: 10px 0; border: 0px solid #d70510;">
            <tr>
                <td style="border: 0; padding:5px; margin:0; background-color: #D80410; color: #f1f1f1; text-align: center; font-size:small;" colspan="3">Pagamento por MB Way</td>
            </tr>
            <tr>
                <td style="padding: 10px 10px 0 10px;"><label for="<?php echo $_code ?>_mbway_phone_number" class="required"><em>*</em><?php echo $this->__('Insira o número de telefone') ?></label><input style="width:100% !important" type="text" title="<?php echo $this->__('Número Mbway:') ?>" placeholder="<?php echo $this->__('Número Mbway') ?>" class="input-text required-entry" id="<?php echo $_code ?>_mbway_phone_number" name="payment[mbway_phone_number]" value="<?php echo $this->htmlEscape($this->getInfoData('mbway_phone_number')) ?>" />
            </tr>
            <tr>
                <td style="border: 0; padding:10px; margin:0; color: #666; font-size:small;"><?php echo $this->__('Se ainda não instalou  a aplicação no smartphone ou ainda não aderiu ao serviço mbway, por favor consulte este'); ?> <a target="_blank"  href="https://www.mbway.pt/" >link</a>. </p></td>
            </tr>
        </table>
    </ul>
</fieldset>

