<table border="0" cellspacing="1" cellpadding="0">

  <tr>
    <td><table width="100%" border="0" cellspacing="1" cellpadding="0">
        <tr style=" font-size:small; border:0;">
          <td rowspan="4" style=" font-size:small;padding: 0px 15px;vertical-align: middle; border:0; "><img src="https://seguro.eupago.pt/repositorio/imagens/MBWay.png" style="margin-bottom: 0px; margin-right: 5px;"></td>
        <tr>
          <td style="padding-right:5px;"><?php echo $this->__('<strong>Telefone:</strong>'); ?></td>
          <td style="padding-right:5px;"><?php echo $this->htmlEscape($this->getInfo()->getEupago_mbw_alias()) ?></td>
        </tr>
        <tr>
          <td style="padding-right:5px;"><?php echo $this->__('<strong>Referência:</strong>'); ?> </td>
          <td style="padding-right:5px;"><?php echo $this->htmlEscape($this->getInfo()->getEupago_mbw_referencia()); ?></td>
        </tr>
        <tr>
          <td style="padding-right:5px;"><?php echo $this->__('<strong>Montante:</strong>'); ?></td>
          <td style="padding-right:5px;"><?php echo number_format($this->htmlEscape($this->getInfo()->getEupago_mbw_montante()),'2',',','') . ' EUR'; ?></td>
        </tr>
    </table></td>
  </tr>
</table>